-- lua neovim packer configs

require('settings')
require('keymappings')
require('packer-config')
require('color-config.nightfox')
require('nvim-tree-config')
require('nvim-notify-config')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('lsp-config.luasnip')
require('lualine-config')
require('barbar-config')
require('treesitter-config')
require('telescope-config')
require('autopairs-config')
require('toggleterm-config')
require('comment-config')
require('which-key-config')
-- require('null-ls-config')

